Fix hard freezes and random reboots
this lib is anyway in vendor and moving it to system is
causing a lot of hard freezes and random reboots,
also spamming logcat:

01-08 20:02:15.317  2904  2904 D /vendor/bin/chre: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1916: Error 0xffffffff: apps_dev_init failed for domain 0, errno Operation not permitted
01-08 20:02:15.318  2904  2904 D /vendor/bin/chre: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2009: Error 0xffffffff: open_dev (-1) failed for domain 0
01-08 20:02:15.318  2904  2904 D /vendor/bin/chre: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:931: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 5 on domain 0 (sc 0x5020000)